### ISSUE TITLE
Support a res$send variant that doesn't convert data to character?

### ISSUE THREAD

**Issue by MilesMcBain** [devOpifex/ambiorix#44]
Neat package!

I used it to conjure up a vector tile server with very little code, but I'm having a problem, which I think is because my tile data (raw vector) is getting transformed to text by the `as.character()` in `res$send()`. There doesn't seem to a `res$send` variant that will let me send my data as binary (`Content-Type: application/x-protobuf`). 

Would you consider adding this? Or accepting a PR?

**Comment by JohnCoene** [comment]
Thanks!

I will have to add something to better handle this.
However, httpuv only allows returning a character vector of length 1.

By raw vector do you mean something like the output of `charToRaw`?
If so, I'm guessing `paste0(x, collapse ="")` would be enough (until I provide something better)

**Comment by MilesMcBain** [comment]
In the response body `httpuv` supports character vector or raw vector. See: https://github.com/rstudio/httpuv/issues/216

In this case by raw vector I mean a protocol buffer. I don't think your work around would work for me as I don't control the receiver, and it's expecting binary.

**Comment by JohnCoene** [comment]
OK. Can you reinstall the latest dev version and try again?
It should not convert your response body to character.

**Comment by JohnCoene** [comment]
If that still does not work could you share a reproducible example?

**Comment by JohnCoene** [comment]
OK, I truly fixed it now, this works.
Requires latest Github version.

```r
library(ambiorix)

img <- "https://www.r-project.org/logo/Rlogo.png"

temp <- tempfile(fileext = ".png")
download.file(img, temp)

size <- file.info(temp)$size
con <- file(temp, "rb")
raw <- readBin(con, raw(), size)
unlink(temp, force = TRUE)
close(con)

print(class(raw))

# core app
app <- Ambiorix$new()

app$get("/", \(req, res){
  res$header("Content-Length", size)
  res$header("Content-Type", "image/png")
  res$send(raw)
})

app$start()
```

**Comment by MilesMcBain** [comment]
Thanks! I see the same thing, raw content coming through untransformed.
