### ISSUE TITLE
Content-Type header is overridden by send defaults (doco issue?)

### ISSUE THREAD

**Issue by MilesMcBain** [devOpifex/ambiorix#45]
I found this example in the doco for response headers:

```
app$get("/hello", \(req, res){
  res$header("Content-Type", "something")
  res$send("Using {ambiorix}!")
})
```

The problem is that `send()` has a default for the `headers` arg: `content_html()` which will replace the custom `Content-Type` header `something` with `text/html`.

**Comment by JohnCoene** [comment]
Yes, I just noticed that looking at your previous issue. Pushed a fix.
