### ISSUE TITLE
Not available from CRAN anymore ?

### ISSUE THREAD

**Issue by waghanza** [devOpifex/ambiorix#52]
Hi @JohnCoene,

Recently I updated https://web-frameworks-benchmark.netlify.app/result.

After digging about `ambiorix` results, I find that this package is not available anymore in CRAN
https://cran.r-project.org/package=ambiorix

The description I use in https://github.com/the-benchmarker/web-frameworks/blob/0826fd3bb0e0b5827285e0ac2107ccee4dcbf9df/r/ambiorix/DESCRIPTION#L1

Regards,

**Comment by rpodcast** [comment]
I just discovered that ambiorix was removed from CRAN again (check results available [here](https://cran-archive.r-project.org/web/checks/2022/2022-10-03_check_results_ambiorix.html)). @JohnCoene  do you have plans to re-submit?

**Comment by JohnCoene** [comment]
@rpodcast Thanks for reporting this, I just noticed that, I'm not sure how I missed it. I've resubmitted, since it was archived it has to go through a manual review though.

Curious how you noticed? Do you use ambiorix?

**Comment by rpodcast** [comment]
@JohnCoene  thank you so much! I am starting to get familiar with `{ambiorix}` to evaluate its feasibility in a couple of use cases. The biggest one is how I'm starting to find myself wanting to create multi-page Shiny apps where the pages are actually pages, and not still one entire process. Colin Fay has addressed this somewhat with [`{brochure}`](https://github.com/ColinFay/brochure), but it doesn't offer the flexbility that ambiorix provides. I'd be open to discussing my additional use cases anytime!
