### ISSUE TITLE
Small typo in code

### ISSUE THREAD

**Issue by hongyuanjia** [devOpifex/ambiorix#55]
A minimal hello world example of {ambiorix} gives an error log

```r
app <- ambiorix::Ambiorix$new()

app$get("/", \(req, res) {
    res$send("Hello World!")
})

app$start()
```

```
✔ 07-01-2024 13:14:16 Listening on http://localhost:31739
Error in inerits(x, "error") : could not find function "inerits"
> ℹ 07-01-2024 13:14:16 GET on /
✖ 07-01-2024 13:14:16 GET on /favicon.ico - Not found
```

The line below should be `inherits` instead of `inherits.`

https://github.com/devOpifex/ambiorix/blob/12727999880ce581fafee391458109c9a443e51e/R/utils.R#L20

**Comment by hongyuanjia** [comment]
Just noticed that #54 fixed it. Close now.

**Comment by JohnCoene** [comment]
Yes it's fixed, sorry for that!
